#!/bin/bash
#Populate bloc database

OUTPUT=/home/konig/Software/bloc/bloc.db

function usage {
	echo "Usage: populate-bloc [options]
    -h		print this message 
    -v 		verbose
    -o 		specify output database file. default: ~/Software/bloc/bloc.db"
}

if test -n "$1"; then
case $1 in
	-o)
		OUTPUT=$2
		;;
	-h)
		usage
		exit
		;;
	-v)
		verbose=true
		;;
	
	*)
		usage
		exit
		;;
esac
fi

(find / 2>/dev/null > $OUTPUT)

if [ $verbose ]; then
echo "Generating database file on $OUTPUT"
fi
