#!/bin/bash
#
# Searches system for a file or directory

database=#DEFAULT
#$HOME/Software/bloc/bloc.db
searcher='rg -Np'
dataout=""
file=""

function help {
echo "Usage: bloc [OPTIONS] FILE
Searches system for a file or directory
    -h, --help 			displays this help message and exits.
    -c <database>		specifies where to load the database from
    -s <searcher>		specifies searcher to be used. Defaults to ripgrep. Additional commands may be used within '' i.e. 'grep -v'
    -v, --verbose		verbose
    -v2, -vv 			Second verbosity level, outputs more information
    -p, --populate <output>	populate bloc database and saves it to <output>. If no arguments are given it defaults to #DEFAULT"
}



if [ $# -gt 0 ]; then
while [ -n "$1" ]
do
	case $1 in
	-c) 	shift 
		database=$1
		;;
	-s) 	shift
		searcher=$1
		;;
	-v|--verbose|-v2|-vv)
		verbose=true
		v=$1
		;;
	-h|--help)	
		help
		exit
		;;	
	--populate|-p) 
		populate=true
		if [ $# -gt 0 ]; then
			case $2 in
				-*)
					;;
				*)
					shift
					dataout=$1
					;;
			esac
		fi
		;;	
	*)	
		file=$1
		search=true
		;;
	esac
shift
done

if [ $populate ]; then
	if [ -n $dataout ]; then
		if [ $verbose ]; then
			bloc-populate $v -o $dataout
		else
			bloc-populate -o $dataout
		fi
	else
		if [ $verbose ]; then
			bloc-populate $v
		else
			bloc-populate
		fi
	fi
fi

if [ $search ]; then
	($searcher $file $database)
	if [ $verbose ]; then
		echo "Searched for `tput setaf 1`\"$file\" `tput sgr0`with database:`tput setaf 1`[$database] `tput sgr0`using `tput setaf 1`\"$searcher\"`tput sgr0`"
	fi
fi

else
	help
fi 



