#!/bin/bash
#Populate bloc database

output=#DEFAULT

function usage {
	echo "Usage: populate-bloc [options]
    -h, --help			print this message 
    -v, --verbose 		verbose
    -vv,-v2			second verbosity level, more data shown
    -o <output.db>		specify output database file. default: #DEFAULT"
}

if [ $# -gt 0 ]; then
while [ -n "$1" ]
do
case $1 in
	-o)
		shift
		case $1 in
			-*|"")
				;;
			*)
				output=$1
				;;
		esac
		;;
	-h|--help)
		usage
		exit
		;;
	-v|--verbose)
		verbose=true
		;;
	-v2|-vv)
		verbose=true
		verbose2=true
		;;
	
	*)
		usage
		exit
		;;
esac
shift
done
fi

if [ $verbose2 ]; then
	find / > $output
else
	(find / 2>/dev/null > $output)
fi

if [ $verbose ]; then
	echo "Generated database file on $output"
fi
